apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-338003
  artifacts:
    - image: gcr.io/ticketing-dev-338003/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            # where to sync this file to inside our running container
            dest: ./

    # # local image: kenoseni/auth
    - image: gcr.io/ticketing-dev-338003/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # tell skaffold to watch the following files
      sync:
        manual:
          - src: "src/**/*.ts"
            # where to sync this file to inside our running container
            dest: ./

    #local image: kenoseni/tickets
    - image: gcr.io/ticketing-dev-338003/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      # tell skaffold to watch the following files
      sync:
        manual:
          - src: "src/**/*.ts"
            # where to sync this file to inside our running container
            dest: ./

    #local image: kenoseni/orders
    - image: gcr.io/ticketing-dev-338003/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      # tell skaffold to watch the following files
      sync:
        manual:
          - src: "src/**/*.ts"
            # where to sync this file to inside our running container
            dest: ./
